#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/7906d9a5-a813-4291-b0a0-0f7d93d9815c 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float energy;
  float height;
  float distance;
  float velocity;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#define TRIGGER D1
#define ECHO    D2

#include "thingProperties.h"
int back = 0;


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  
  pinMode(TRIGGER, OUTPUT);
  pinMode(ECHO, INPUT);
  pinMode(BUILTIN_LED, OUTPUT);
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  long duration;
  float distance;
  digitalWrite(TRIGGER, LOW);  
  delayMicroseconds(2); 
  
  digitalWrite(TRIGGER, HIGH);
  delayMicroseconds(10); 
  
  digitalWrite(TRIGGER, LOW);
  duration = pulseIn(ECHO, HIGH);
  distance = (duration/2) / 2910;
  velocity = (distance-back)/0.3;
  
  Serial.print(distance);
  Serial.println("m");
  Serial.print(velocity);
  Serial.println("m/s");
  delay(300);
  back = distance;
  height = 0.5 * distance;
  energy = 0.005 * (0.5*velocity*velocity + 9.8 * height);
}

/*
  Since Distance is READ_WRITE variable, onDistanceChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDistanceChange()  {
  // Add your code here to act upon Distance change
}

/*
  Since Height is READ_WRITE variable, onHeightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHeightChange()  {
  // Add your code here to act upon Height change
}

/*
  Since Energy is READ_WRITE variable, onEnergyChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onEnergyChange()  {
  // Add your code here to act upon Energy change
}

/*
  Since Velocity is READ_WRITE variable, onVelocityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onVelocityChange()  {
  // Add your code here to act upon Velocity change
}